### ISSUE TITLE
Idofront nms BukkitEntity alias should either be moved out of nms or removed/called out in documentation

### ISSUE THREAD

**Issue by Derongan** [MineInAbyss/Idofront#15]
Documentation references BukkitEntity heavily in the entity section. Its intuitive that this requires you to bring in the idofront-nms dependency and I would argue not the right place for the alias to live.

**Comment by 0ffz** [comment]
Yep this was an accident, feel free to move it and make pr, or i'll get around to it eventually

**Comment by 0ffz** [comment]
Fixed in recent update
